2021-06-03 20:34:16 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "'' (RECIPE: ""TIME_TAKEN"" INTEGER NOT NULL)"
Data conversion error converting "'' (RECIPE: ""TIME_TAKEN"" INTEGER NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."RECIPE"("ID","DESCRIPTION","DIFFICULTY","IMAGE","NAME","RATE","STEPS","TIME_TAKEN")VALUES(?,?,?,?,?,?,?,?) [22018-200]
2021-06-03 20:34:16 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "'' (RECIPE: ""TIME_TAKEN"" INTEGER NOT NULL)"
Data conversion error converting "'' (RECIPE: ""TIME_TAKEN"" INTEGER NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."RECIPE"("ID","DESCRIPTION","DIFFICULTY","IMAGE","NAME","RATE","STEPS","TIME_TAKEN")VALUES(?,?,?,?,?,?,?,?) [22018-200]
2021-06-03 21:16:39 jdbc[14]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No hay datos disponibles.
No data is available [2000-200]
2021-06-03 21:17:41 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "DROP *[*] FROM MEASURE"; se esperaba "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"
Syntax error in SQL statement "DROP *[*] FROM MEASURE"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP * from measure [42001-200]
2021-06-03 21:17:47 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "DROP *[*] FROM TABLE MEASURE"; se esperaba "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"
Syntax error in SQL statement "DROP *[*] FROM TABLE MEASURE"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP * from table measure [42001-200]
2021-06-03 21:23:02 jdbc[25]: null
org.h2.message.DbException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexión no fue cerrada por la aplicación y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 18 more
2021-06-03 21:23:40 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "'2.5' (INGREDIENT_MEASURE: ""QUANTITY"" INTEGER)"
Data conversion error converting "'2.5' (INGREDIENT_MEASURE: ""QUANTITY"" INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."INGREDIENT_MEASURE"("ID","QUANTITY","INGREDIENT_ID","MEASURE_ID","RECIPE_ID")VALUES(?,?,?,?,?) [22018-200]
2021-06-03 21:23:40 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "'2.5' (INGREDIENT_MEASURE: ""QUANTITY"" INTEGER)"
Data conversion error converting "'2.5' (INGREDIENT_MEASURE: ""QUANTITY"" INTEGER)"; SQL statement:
INSERT INTO "PUBLIC"."INGREDIENT_MEASURE"("ID","QUANTITY","INGREDIENT_ID","MEASURE_ID","RECIPE_ID")VALUES(?,?,?,?,?) [22018-200]
2021-06-03 21:26:42 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "'nulll' (INGREDIENT_MEASURE: ""MEASURE_ID"" BIGINT)"
Data conversion error converting "'nulll' (INGREDIENT_MEASURE: ""MEASURE_ID"" BIGINT)"; SQL statement:
INSERT INTO "PUBLIC"."INGREDIENT_MEASURE"("ID","QUANTITY","INGREDIENT_ID","MEASURE_ID","RECIPE_ID")VALUES(?,?,?,?,?) [22018-200]
2021-06-03 21:26:42 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "'nulll' (INGREDIENT_MEASURE: ""MEASURE_ID"" BIGINT)"
Data conversion error converting "'nulll' (INGREDIENT_MEASURE: ""MEASURE_ID"" BIGINT)"; SQL statement:
INSERT INTO "PUBLIC"."INGREDIENT_MEASURE"("ID","QUANTITY","INGREDIENT_ID","MEASURE_ID","RECIPE_ID")VALUES(?,?,?,?,?) [22018-200]
2021-06-03 22:23:43 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "'' (INGREDIENT_MEASURE: ""ID"" BIGINT DEFAULT NEXT VALUE FOR ""PUBLIC"".""SYSTEM_SEQUENCE_495DB46B_3114_42C4_ADFB_186BDCAF07EA"" NOT NULL NULL_TO_DEFAULT SEQUENCE ""PUBLIC"".""SYSTEM_SEQUENCE_495DB46B_3114_42C4_ADFB_186BDCAF07EA"")"
Data conversion error converting "'' (INGREDIENT_MEASURE: ""ID"" BIGINT DEFAULT NEXT VALUE FOR ""PUBLIC"".""SYSTEM_SEQUENCE_495DB46B_3114_42C4_ADFB_186BDCAF07EA"" NOT NULL NULL_TO_DEFAULT SEQUENCE ""PUBLIC"".""SYSTEM_SEQUENCE_495DB46B_3114_42C4_ADFB_186BDCAF07EA"")"; SQL statement:
INSERT INTO "PUBLIC"."INGREDIENT_MEASURE"("ID","QUANTITY","INGREDIENT_ID","MEASURE_ID","RECIPE_ID")VALUES(?,?,?,?,?) [22018-200]
2021-06-03 22:23:43 jdbc[14]: exception
org.h2.jdbc.JdbcSQLDataException: Conversión de datos fallida, convirtiendo "'' (INGREDIENT_MEASURE: ""ID"" BIGINT DEFAULT NEXT VALUE FOR ""PUBLIC"".""SYSTEM_SEQUENCE_495DB46B_3114_42C4_ADFB_186BDCAF07EA"" NOT NULL NULL_TO_DEFAULT SEQUENCE ""PUBLIC"".""SYSTEM_SEQUENCE_495DB46B_3114_42C4_ADFB_186BDCAF07EA"")"
Data conversion error converting "'' (INGREDIENT_MEASURE: ""ID"" BIGINT DEFAULT NEXT VALUE FOR ""PUBLIC"".""SYSTEM_SEQUENCE_495DB46B_3114_42C4_ADFB_186BDCAF07EA"" NOT NULL NULL_TO_DEFAULT SEQUENCE ""PUBLIC"".""SYSTEM_SEQUENCE_495DB46B_3114_42C4_ADFB_186BDCAF07EA"")"; SQL statement:
INSERT INTO "PUBLIC"."INGREDIENT_MEASURE"("ID","QUANTITY","INGREDIENT_ID","MEASURE_ID","RECIPE_ID")VALUES(?,?,?,?,?) [22018-200]
